### ISSUE TITLE
Quest information in ToolTip

### ISSUE THREAD

**Issue by Pufca** [IrcDirk/Carbonite-Classic#159]
![Bez názvu](https://user-images.githubusercontent.com/85056881/120098826-5565db00-c138-11eb-96c5-e5035ae36ff9.png)

Hi guys can u help me ? Why i dont see q info  on marked zone ( picture)  ? Example move cursor on mob and see 5/8 slain or loot q item etc . 
Thank you

**Comment by IrcDirk** [comment]
Becouse this is not available in TBC. U can use Questie for this.

**Comment by Pufca** [comment]
> 
> 
> Becouse this is not available in TBC. U can use Questie for this.

But in 2.4.3 build is available . I dont want questie bcs I've been using it for many years and I'm used to it and I don't want to change it

**Comment by Pufca** [comment]
![Bez názvu](https://user-images.githubusercontent.com/85056881/120116089-b61c0480-c186-11eb-8551-e2fbb3be8bd9.png)
Here is picture from 2.4.3 build free server and here its working is there any differents between free severs and oficial ? And its possible upgrade 2.4.3 build to 2.5.1 ? I notest that most of 1.13 version addons where updated 2.5.1 could be 2.4.3 addons upgraded to 2.5.1 as well ? Is it more difficult ?

**Comment by Pufca** [comment]
![Bez názvu](https://user-images.githubusercontent.com/85056881/120116275-b8cb2980-c187-11eb-9288-b329b3bbf251.png)
From same server like picture up

**Comment by IrcDirk** [comment]
New TBC 2.5.1 lua API is from Shadowlands so no way to convert old 2.4.3 lua to new 2.5.1. No addon from 2.4.3 will work with 2.5.1

**Comment by IrcDirk** [comment]
Ok, it though that i need to scrap more data but it seems i already got it. Pushed commit with data https://github.com/IrcDirk/Carbonite-Classic/commit/2d596a23af3e21db8e7f797dccdacf498ac3df54 and made some modifications and it should work now ;)

**Comment by Pufca** [comment]
![Bez názvu](https://user-images.githubusercontent.com/85056881/120221667-166e7d00-c23f-11eb-8cc0-5c1c04d1a631.png)
If my procedure was correct, it still doesn't work. If I made a mistake somewhere, please fix it

**Comment by IrcDirk** [comment]
Those NPC are in Units2Quests database, this should work. U did all u should so thats fine.

Do u have this option enabled:

![obraz](https://user-images.githubusercontent.com/1030023/120225409-78ca7c00-c245-11eb-91bb-246b2113e18e.png)

**Comment by IrcDirk** [comment]
U did restart WoW client after update from repo? Normal reload would not work in this case.

**Comment by IrcDirk** [comment]
Works fine on my side:

![obraz](https://user-images.githubusercontent.com/1030023/120227234-15424d80-c249-11eb-82f0-a438e9d488ad.png)

**Comment by Pufca** [comment]
Eureka ! You are fkin BOSS ! I hope it will still show quests well and finally I will have the best function addon in the game again. After the payout I will have to send some money to donate. Well done ! You can lock topic.

**Comment by IrcDirk** [comment]
Ill leave it open for some time till ill release this option to public :)
